logging:
  level:
    .: error
    org.springframework: ERROR
    c: ERROR

spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"
---
spring:
  profiles: dev
jira:
  instances:
    - name: JIRA1
      url: http://JIRA1.com
      username: abc
      password: abc@123
    - name: JIRA2
      url: http://JIRA2.com
      username: abc
      password: abc@123
---
spring:
  profiles: prod
jira:
  instances:
    - name: JIRA1
      url: http://JIRA1.com
      username: abc
      password: abc@123
    - name: JIRA2
      url: http://JIRA2.com
      username: abc
      password: abc@123